// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119011129_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Package", b =>
                {
                    b.Property<int>("PackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PackageID"));

                    b.Property<DateTime>("DeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPickedUp")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostalService")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResidentID")
                        .HasColumnType("int");

                    b.HasKey("PackageID");

                    b.HasIndex("ResidentID");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("FinalProject.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int")
                        .HasColumnName("unit_number");

                    b.HasKey("Id");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("FinalProject.Models.Staff", b =>
                {
                    b.Property<string>("staff_username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("staff_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("staff_username");

                    b.ToTable("StaffLogin");
                });

            modelBuilder.Entity("FinalProject.Models.UnknownPackage", b =>
                {
                    b.Property<int>("UnknownPackageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UnknownPackageID"));

                    b.Property<DateTime>("DeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NameOnPackage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalService")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UnknownPackageID");

                    b.ToTable("UnknownPackages");
                });

            modelBuilder.Entity("FinalProject.Models.Package", b =>
                {
                    b.HasOne("FinalProject.Models.Resident", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentID");

                    b.Navigation("Resident");
                });
#pragma warning restore 612, 618
        }
    }
}
